# -*- coding: utf-8 -*-
"""dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lRGHGU_NitMLsC2mOLrCH-CwGSS33TOL
"""

import streamlit as st
from PIL import Image

st.set_page_config(
    page_title="ECG Anomaly Detection Report",
    layout="wide"
)

# Utility function
def show_img(path, caption=None, width=None):
    st.image(Image.open(path), caption=caption, use_column_width=width is None, width=width)

# Title
st.title("ECG Anomaly Detection: Final Report")
st.markdown("""
This report presents the end-to-end findings from a real-time ECG Anomaly Detection system developed using Isolation Forest and Kafka-based streaming.
It includes model behavior, drift analysis, anomaly interpretation, and recommendations.

---
""")

# SECTION 1: Introduction
st.header("1. Project Objective")
st.markdown("""
The goal of this project was to **detect anomalous patterns in ECG signals in real-time**, simulate production-like behavior using Kafka,
and automatically handle model updates in the presence of **concept drift**.

We built:
- A streaming pipeline using **Apache Kafka**
- Anomaly detection with **Isolation Forest**
- Drift detection using **distributional change (KS-test)**
- Model retraining logic
- Visual & explainability insights using **matplotlib** and **Streamlit**
""")

# SECTION 2: System Architecture
st.header("2. System Design")
st.markdown("""
The pipeline worked as follows:
1. **Producer** streamed 30,000 ECG rows from the MIT-BIH dataset to Kafka
2. **Consumer** performed real-time anomaly detection
3. When drift was detected, the model was **retrained** and logged
4. Final predictions and model were evaluated at the end
)

# SECTION 3: Real-Time Insights
st.header("3. Real-Time Anomaly Detection")
st.markdown("**Anomalies vs Normal Signals:**")

col1, col2 = st.columns(2)
with col1:
    show_img("results/ecg_waveform_anomalies.png", "ECG Signals with Highlighted Anomalies")
with col2:
    show_img("results/pie_anomaly_dist.png", "Distribution of Predictions (Normal vs Anomaly)", width=400)

st.markdown("**Anomaly Count Over Time:**")
show_img("results/bar_anomaly_per_minute.png", "Anomaly Density per Simulated Minute")

# SECTION 4: Drift Detection
st.header("4. Concept Drift Monitoring")
st.markdown("""
We used **z-score** thresholds and **distributional shift** testing (KS-Test) to detect drift.
If anomaly density spiked beyond a set threshold, retraining was triggered.
""")
show_img("results/zscore_time_series.png", "Z-Score Trend with Anomaly Thresholds")
show_img("results/heatmap_hour_day.png", "Heatmap: Anomalies by Hour and Day")

# SECTION 5: Explainability
st.header("5. Model Interpretability")
st.markdown("""
We extracted raw anomaly scores from the Isolation Forest to visualize how certain predictions were made.
The lower the score, the more likely the instance was anomalous.
""")

col1, col2 = st.columns(2)
with col1:
    show_img("results/anomaly_score_hist.png", "Distribution of Anomaly Scores")
with col2:
    show_img("results/zscore_scatter.png", "Z-Scores of Anomalous Points")

show_img("results/zscore_vs_anomaly_score.png", "Z-Score vs Anomaly Score (ECG1)")

# SECTION 6: Local Anomaly Windows
st.header("6. 🔬 Local ECG Window Around Anomalies")
show_img("results/anomaly_window_view.png", "Snapshot of ECG Signal Around Detected Anomaly")

# SECTION 7: Model Evaluation
st.header("7. 📊 Model Evaluation Summary")
st.markdown("**Simulated Evaluation (2% Anomaly Assumption):**")
show_img("results/confusion_matrix.png", "Confusion Matrix on Prediction Log")

st.markdown("""
**Key Takeaways:**
- **High precision** on anomaly detection (≈98%)
- **Model retraining** helped adapt to drift during streaming
- **Most anomalies** occurred during clustered timestamps (possible batch pattern)
""")

# SECTION 8: Recommendations
st.header("8. 📝 Recommendations")
st.markdown("""
Based on the analysis and streaming behavior:

✅ Implement **batch retraining** once drift is detected, not per anomaly spike
✅ Add **domain rules** (e.g., BPM thresholds) for hybrid logic
✅ Use dashboard in **clinical monitoring setups** with alerting logic
✅ Replace dummy ground truth with expert-labeled ECGs for real validation
""")

# Footer
st.markdown("---")
st.caption("Report generated by Jahnavi Patel · Data Scientist · April 2025")