# -*- coding: utf-8 -*-
"""retraining_module.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pc4xUU5cT_uAhH44BUh1smaIaW0Jeb4t
"""

import pandas as pd
import numpy as np
import joblib
import os
from sklearn.ensemble import IsolationForest
from datetime import datetime

MODEL_PATH = "models/final_model.pkl"
LOG_PATH = "logs/retrain_log.csv"

def retrain_model(data_window):
    # Ensure necessary directories exist
    os.makedirs("models", exist_ok=True)
    os.makedirs("logs", exist_ok=True)

    # Prepare training data
    X = np.array(data_window).reshape(-1, 2)  # assuming ECG1 and ECG2

    # Train new model
    new_model = IsolationForest(contamination=0.02, random_state=42)
    new_model.fit(X)

    # Save as final model (overwrite)
    joblib.dump(new_model, MODEL_PATH)

    # Log retraining event
    now = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    log_entry = pd.DataFrame([{
        "timestamp": now,
        "model": "final_model.pkl",
        "samples_used": len(data_window)
    }])

    if os.path.exists(LOG_PATH):
        log_entry.to_csv(LOG_PATH, mode='a', header=False, index=False)
    else:
        log_entry.to_csv(LOG_PATH, index=False)

    print(f"Final model retrained and saved as final_model.pkl")
    return MODEL_PATH