# -*- coding: utf-8 -*-
"""utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-kazkAQwvRkrH7nFGDyXzFCKOXOpkcPO
"""

from scipy.stats import ks_2samp
import numpy as np

# Global variables
baseline_window = []
WINDOW_SIZE = 500

def format_ecg_input(ecg1, ecg2):
    return np.array([[ecg1, ecg2]])

def update_drift_window(window, new_point):
    window.append(new_point)
    if len(window) > WINDOW_SIZE:
        window.pop(0)
    return window

def check_drift(current_window, p_thresh=0.01):
    global baseline_window

    # Not enough data to compare yet
    if len(baseline_window) < WINDOW_SIZE:
        baseline_window += current_window
        return False

    # Compare distributions
    current_flat = np.array(current_window).flatten()
    baseline_flat = np.array(baseline_window[:WINDOW_SIZE]).flatten()

    stat, p_value = ks_2samp(baseline_flat, current_flat)
    return p_value < p_thresh